### ISSUE TITLE
Use Python for dev container startup logic

### ISSUE THREAD

**Issue by ehrhorn** [GlazeTech/TeraStore#52]
We may think about using a Python script for the startup logic for `./scripts/dev_up.sh`. We can even add the script (and one for `dev_down.sh`) to `pyproject.toml`, making life easier for the developer:

```toml
[project.scripts]
my-client = "my_package.my_module:main_cli"
```

This is built in functionality from Setuptools, which installs the script as an executable in your virtual environment.
